<?php echo $this->doctype() ?>
<?php
//$controller = 'user';
//$action = 'login';

$title = $this->sysConfig('design/head/default_title');
?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?=strip_tags($title)?></title>
    <!--<meta name="author" content="Agere Company" />
    <meta name="description" content="Agere Cloud - Business System" />
    <meta name="keywords" content="e-commerce" />
    <meta name="application-name" content="Agere Cloud - Business System" />
-->
    <meta name="copyright" content="<?php //echo getValueOf("meta_copyright") ?>" />
    <meta name="robots" content="none" />
    <meta http-equiv="Content-Language" content="ru" />

    <!--<link rel="stylesheet" href="<?/*= $this->basePath() */?>/media/css/main.min.css?40" type="text/css" />
    <link  rel="stylesheet" href="<?/*= $this->basePath() */?>/media/css/custom.min.css?40" type="text/css" />-->

    <!--<script src="/media/js/jquery/jquery-1.9.1.min.js"></script>
    <script src="/media/js/menu-drop-down.js?40"></script>-->
</head>

<body class="<?= $this->current('controller') . '-' . $this->current('action') ?>">
<noscript>Для корректной работы <a href="https://www.google.com.ua/search?q=включить+javascript" target="_blank">включите джава скрипты</a> и обновите страницу</noscript>
<div class="wrapper">
    <div class="content-wrapper clearfix">
        <div class="context-layout">
            <?= $this->content ?>
        </div>
    </div>
</div>
</body>
</html>
