<?php
/** @var \Popov\Agere\View\Helper\Form $formAgereHelper */
$formAgereHelper = $this->formAgere();

/** @var \Popov\Supplier\View\Helper\Supplier $supplierHelper */
$supplierHelper = $this->supplier();

$controller = $this->layout()->route->getParam('controller');
$action = $this->layout()->route->getParam('action');
?>

<div id="tabs" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
	<div id="credit-extend" aria-labelledby="ui-id-2" class="ui-tabs-panel ui-widget-content ui-corner-bottom" style="padding: 2px;width: 70%" aria-expanded="true" aria-hidden="false">

		<?=$this->form()->openTag($form)?>
		<fieldset>
			<legend class="input_heading">Основные данные</legend>

			<!--<table class="main-calculation-data width tableinput">
				<tr>
					<td style="padding-right: 10px">
						<?php /*$formName = $form->get('photo'); */?>
						<?php /*if ($formName->getValue() != '') { */?>
							<img src="/files/get/<?/*=$id*/?>/document/users/file/<?/*=$formName->getValue()*/?>" width="300">
							<span class="hide">фото</span>
							<?php
/*							$buttonsArgs['delete'] = [
								'href'			=> $this->url('default/id', [
									'controller'	=> $controller,
									'action'		=> 'delete-file',
									'id'			=> $id
								]),
								'class'			=> $controller,
								'controller'	=> $controller,
								'action'		=> 'delete-file',
							];

							echo $this->buttons('deleteFile', $buttonsArgs);
							*/?>
						<?php /*} */?>
						<?/*=$this->formRow($formName)*/?>
					</td>
					<td>-->
						<table class="main-calculation-data width tableinput">
							<tbody>
							<tr>
								<td><?=$fields['email']?></td>
								<td><?=$this->formRow($form->get('email'))?></td>
							</tr>
							<tr>
								<td>Пароль старый</td>
								<td><?=$this->formPassword($form->get('passwordOld')).$this->formElementerrors($form->get('passwordOld'))?></td>
							</tr>
							<tr>
								<td>Пароль новый</td>
								<td>
									<?=$this->formPassword($form->get('password'))?>
									<p class="hint">Минимальный размер для пароля - 6 символов. Пароль должен содержать цифры и буквы.</p>
									<?=$this->formElementerrors($form->get('password'))?>
								</td>
							</tr>
							<tr>
								<td><?=$fields['firstName']?></td>
								<td><?=$this->formRow($form->get('firstName'))?></td>
							</tr>
							<tr>
								<td><?=$fields['lastName']?></td>
								<td><?=$this->formRow($form->get('lastName'))?></td>
							</tr>
							<tr>
								<td><?=$fields['patronymic']?></td>
								<td><?=$this->formRow($form->get('patronymic'))?></td>
							</tr>
							<tr>
								<td><?=$fields['phone']?></td>
								<td><?=$this->formRow($form->get('phone'))?></td>
							</tr>
							<tr>
								<td><?=$fields['phoneWork']?></td>
								<td><?=$this->formRow($form->get('phoneWork'))?></td>
							</tr>
							<tr>
								<td><?=$fields['phoneInternal']?></td>
								<td><?=$this->formRow($form->get('phoneInternal'))?></td>
							</tr>
							<tr>
								<td><?=$fields['post']?></td>
								<td><?=$this->formRow($form->get('post'))?></td>
							</tr>
							<tr>
								<td><?=$fields['dateBirth']?></td>
								<td><?=$this->formRow($form->get('dateBirth')->setAttribute('class', 'datepicker'))?></td>
							</tr>
							<tr>
								<td><?=$fields['dateEmployment']?></td>
								<td><?=$this->formRow($form->get('dateEmployment')->setAttribute('class', 'datepicker'))?></td>
							</tr>
							<tr>
								<td><?=$fields['supplierId']?></td>
								<td>
									<?php
									$formName = $form->get('supplierId');
									?>
									<select<?=$formAgereHelper->strAttributes($formName->getAttributes())?>><?=$supplierHelper->supplierList($formName->getValue(), 'Выберите поставщика')?></select>
									<?=$this->formElementerrors($formName)?>
								</td>
							</tr>
							<tr>
								<td><?=$fields['showIndex']?></td>
								<td><?=$this->formRow($form->get('showIndex'))?></td>
							</tr>
							<tr>
								<td><?=$fields['notation']?></td>
								<td>
									<textarea name="notation"><?=$form->get('notation')->getValue()?></textarea>
								</td>
							</tr>
						</tbody>
					</table>
				<!--</td>
			</tr>
		</table>-->

		</fieldset>

		<div class="button-place">
			<?php
			$buttonsArgs['save'] = [
				'type'       => 'submit',
				'attr'       => [
					'class' => 'button',
				],
				'controller' => $controller,
				'action'     => $action,
			];

			echo $this->buttons('saveItem', $buttonsArgs);
			?>
		</div>

		<?=$this->form()->closeTag()?>

	</div>
</div>

<script>
	jQuery('[name=dateBirth], [name=dateEmployment]').datepicker({
		changeMonth: true,
		changeYear: true,
		yearRange: '1920:',
		dateFormat: 'dd/mm/yy'
	});
</script>