<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Забыли пароль?</title>
	<link rel="stylesheet" href="/media/css/main.min.css?40" type="text/css" />
	<link  rel="stylesheet" href="/media/css/custom.min.css?40" type="text/css" />
</head>

<body>
<?=$this->form()->openTag($form)?>
	<table border="0" align="center" class="form-login">
		<tbody>
		<tr>
			<td valign="top">
				<table width="250" cellspacing="0" cellpadding="4" border="0" class="cmsMainText">
					<tbody>
					<tr>
						<td class="labels lable_login">Email</td>
					</tr>
					<tr>
						<td class="input_login"><?=$this->formRow($form->get('email'))?></td>
					</tr>
					<tr>
						<td height="30" align="left" class="buttons" style="padding-left:30px">
							<input type="submit" value="Выслать пароль">
						</td>
					</tr>
					</tbody>
				</table>
			</td>
		</tr>
		</tbody>
	</table>
<?=$this->form()->closeTag()?>

<?php if (! $errorsCount && $issetSaveData) { ?>
	<script language="javascript">
		self.close();
	</script>
<?php } ?>

</body>
</html>