<?=$this->form()->openTag($form)?>
<table border="0" align="center" class="form-login">
    <tbody>
    <tr>
        <?php /*<td width="50%" style="vertical-align: top; height: 400px; background-image: url('/assets/images/left_background.jpg'); background-position: right; background-repeat: no-repeat;"></td>*/ ?>
        <td valign="top">
            <table width="250" cellspacing="0" cellpadding="4" border="0" class="cmsMainText">
                <tbody>
                <tr>
                    <td height="30px" colspan="2"><div class="CmsMainHeader">Login to the System</div></td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                    <td class="labels lable_login">Email</td>
                </tr>
                <tr>
                    <td class="input_login"><?=$this->formInput($form->get('email'))?></td>
                </tr>
                <tr>
                    <td class="labels lable_login">Password</td>
                </tr>
                <tr>
                    <td class="input_login">
	                    <?=$this->formPassword($form->get('password')->setAttribute('value', '')) . $this->formElementErrors($form->get('password'))?>
                    </td>
                </tr>
                <?php /*<tr>
                    <td class="labels lable_login">
                        <a onclick="popUpWindow('<?= $this->url('admin/default', [
                            'controller' => $this->current('controller'),
                            'action' => 'forgot-password',
                        ]) ?>', 150, 310)">Forget password?</a>
                    </td>
                </tr>*/ ?>
                <tr>
                    <td height="30" align="left" class="buttons" style="padding-left:30px">
                        <?=$this->formSubmit()->render($form->get('save')->setAttribute('value', 'Login'))?>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>
<?=$this->form()->closeTag()?>
